name: Send Daily Greeting Email # 工作流名称

on:
  schedule:
    # 使用CRON表达式，表示在北京时间每天早上9点运行
    # UTC时间是 1:00，所以北京时间 (UTC+8) 是 9:00
    - cron: '10 1 * * *'
    - cron: '10 8 * * *'
    - cron: '10 12 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的Ubuntu环境

    steps:
    - name: Checkout code # 第一步：检出代码
      uses: actions/checkout@v3

    - name: Set up Python # 第二步：设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # 指定你的Python版本

    - name: Install dependencies # 第三步：安装依赖
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script # 第四步：运行你的脚本
      env:
        # 从GitHub Secrets中读取敏感信息
        API_KEY: ${{ secrets.API_KEY }}
        MAIL_KEY: ${{ secrets.MAIL_KEY }}
        MAIL_USER: ${{ secrets.MAIL_USER }}
        RECEIVERS: ${{ secrets.RECEIVERS }}
        LOCATION: ${{ secrets.LOCATION }}
      run: python send.py # 运行你的Python文件
